export const PROJECTS_DATA = [
  {
    id: 0,
    image: './projects/wallesave.png',
    liveLink: 'google.com',
    repoLink: '',
    name: 'Wallesave',
    shortDesc: 'Expenses & incomes tracker',
    desc:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 1,
    image: './projects/wallesave.png',
    liveLink: 'google.com',
    repoLink: '',
    name: 'Wallesave',
    shortDesc: 'Expenses & incomes tracker',
    desc: 'Expenses & incomes tracker',
  },
  {
    id: 2,
    image: './projects/wallesave.png',
    liveLink: 'google.com',
    repoLink: '',
    name: 'Wallesave',
    shortDesc: 'Expenses & incomes tracker',
    desc: 'Expenses & incomes tracker',
  },
  {
    id: 3,
    image: './projects/wallesave.png',
    liveLink: 'google.com',
    repoLink: 'github.com',
    name: 'Wallesave',
    shortDesc: 'Expenses & incomes tracker',
    desc: 'Expenses & incomes tracker',
  },
  {
    id: 4,
    image: './projects/wallesave.png',
    liveLink: 'google.com',
    repoLink: 'github.com',
    name: 'Wallesave',
    shortDesc: 'Expenses & incomes tracker',
    desc: 'Expenses & incomes tracker',
  },
  {
    id: 5,
    image: './projects/wallesave.png',
    liveLink: 'google.com',
    repoLink: 'github.com',
    name: 'Wallesave',
    shortDesc: 'Expenses & incomes tracker',
    desc: 'Expenses & incomes tracker',
  },
];
